name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t vov-django-app -f compose/local/django/Dockerfile .
          docker tag vov-django-app:latest ${{ secrets.DOCKER_USERNAME }}/vov-django-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/vov-django-app:latest